// Ques 26 - Find natural numbers using recusion
/*
function sum(num) {
    if(num > 0) {
        return num + sum(num - 1);
    }
    else {
        return num;
    }
 }
const number = 5;
const result = sum(number);
console.log(`The sum is ${result}`);
 */

//---------------------------------------------------------------

//Ques 27 -program where the user has to guess a number generated by a program
/*
function guessNumber() {
    const random = Math.floor(Math.random() * 10) + 1;
    let number = parseInt(prompt('Guess a number from 1 to 10: '));
    while(number !== random) {
        number = parseInt(prompt('Guess a number from 1 to 10: '));
    }
    if(number == random) {
        console.log('You guessed the correct number.');
    }
  }
guessNumber();
 */

//---------------------------------------------------------------------

// Ques 27 - Program to Shuffle Deck of Cards
/*
// declare card elements
const suits = ["Spades", "Diamonds", "Club", "Heart"];
const values = [
  "Ace",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "Jack",
  "Queen",
  "King",
];
let deck = [];
// create a deck of cards
for (let i = 0; i < suits.length; i++) {
    for (let x = 0; x < values.length; x++) {
        let card = { Value: values[x], Suit: suits[i] };
        deck.push(card);
    }
}
// shuffle the cards
for (let i = deck.length - 1; i > 0; i--) {
    let j = Math.floor(Math.random() * i);
    let temp = deck[i];
    deck[i] = deck[j];
    deck[j] = temp;
}
console.log('The first five cards are:');
// display 5 results
for (let i = 0; i < 5; i++) {
    console.log(`${deck[i].Value} of ${deck[i].Suit}`)
}
 */

//----------------------------------------------------------------

// Ques 29- program to display fibonacci sequence using recursion
/*
function fibonacci(num) {
    if(num < 2) {
        return num;
    }
    else {
        return fibonacci(num-1) + fibonacci(num - 2);
    }
}
const nTerms = 5;
if(nTerms <=0) {
    console.log('Enter a positive integer.');
}
else {
    for(let i = 0; i < nTerms; i++) {
        console.log(fibonacci(i));
    }
}
 */

//--------------------------------------------------------------

//Ques 30 - Find Factorial of Number Using Recursion 
/*
const num = 5;
if(num>=0){
    const res = fact(num);
    console.log(res);
} else{
    console.log("ENter a positive number ")
}
function fact(x){
    if(x==0){
        return 1;
    }
    else{
        return x * fact(x-1);
    }
}
 */

//-------------------------------------------------

// QUes 31 - Program to Convert Decimal to Binary
/*
function convertToBinary(x) {
    let bin = 0;
    let rem, i = 1, step = 1;
    while (x != 0) {
        rem = x % 2;
        console.log(
            `Step ${step++}: ${x}/2, Remainder = ${rem}, Quotient = ${parseInt(x/2)}`
        );
        x = parseInt(x / 2);
        bin = bin + rem * i;
        i = i * 10;
    }
    console.log(`Binary: ${bin}`);
}

let number = 9;
convertToBinary(number);
 */

//-----------------------------------------------------------

//Ques 32 - Program to Find ASCII Value of Character
/*
const string = "r";
const result = string.charCodeAt(0);
console.log(`The ASCII value is: ${result}`);
 */

//-----------------------------------------------------------

//Ques 33 - Check Whether a String is Palindrome or Not
/*
const string = "Yashika";
const value = isPal(string);
console.log(value);
function isPal(string){
    const len = string.length;
    for(let i=0; i<len/2; i++){
        if(string[i] !== string[len-1-i]);{
            return "Not a Palindrom"
        }
    }
    return "palindrome";
}
 */

//-------------------------------------------------------------

//Ques 34 - sort words in alphabetical order
/*
const string = "Hello guys good morning";

// converting to an array
const words = string.split(' ');
words.sort();
console.log('The sorted words are:');

for (const element of words) {
  console.log(element);
}
 */

// ---------------------------------------------------------

//Ques - 35 Program to Replace Characters of a String
/*
const string = 'Mr Red has a red house and a red car';
const newText = string.replace('red', 'blue');
console.log(newText);

*/

//-----------------------------------------------------------

// Ques 36 - Program to Reverse a String
/*
const s = "Yashika";
const res = reverse(s);
console.log(res);
function reverse(s){
    let newstr = "";
    for(let i=s.length-1; i>=0; i--){
        newstr += s[i];
    }
    return newstr;
}
 */

//---------------------------------------------------------------

//Ques 37 - Program to Create Objects in Different Ways
/*
const person = {
    name : 'Yashika',
    age : 20,
    hobbies : ['dancing','reading','coding'],
    greet : function(){
        console.log("Hello everyone");
    },
    score: {
        maths: 90,
        science: 80
    }
}
console.log(person);
console.log(typeof person);

// program to create JavaScript object using instance of an object
const student = new Object ( { 
    name: 'John',
    age: 20,
    hobbies: ['reading', 'games', 'coding'],
    greet: function() {
        console.log('Hello everyone.');
    },
    score: {
        maths: 90,
        science: 80
    }
});

console.log(typeof student); // object

// accessing the object value
console.log(student.name);
console.log(student.hobbies[0]);
student.greet();
console.log(student.score.maths);

// program to create JavaScript object using instance of an object

function std() {
    this.name = 'John',
    this.age = 20,
    this.hobbies = ['reading', 'games', 'coding'],
    this.greet = function() {
        console.log('Hello everyone.');
    },
    this.score = {
        maths: 90,
        science: 80
    }
}
const std = new Person();
console.log(typeof person); 
console.log(std.name);
console.log(std.hobbies[0]);
std.greet();
console.log(std.score.maths);
 */

//-----------------------------------------------------

//Ques 38 - Check the Number of Occurrences of a Character in the String
/*
const str = "Yashika";
const charToCheck = "a";
const result = countstring(str, charToCheck);
console.log(result);
function countstring(str, letter){
    let cnt = 0;
    for(let i=0; i<str.length; i++){
        if(str.charAt(i) == letter){
            cnt++;
        }
    }
    return cnt;
}
 */

//----------------------------------------------------

//Ques 39 - Convert the First Letter of a String into UpperCase
/*
const s = "yashika";
const result = capatilize(s);
console.log(result);
function capatilize(str){
    const capital = str.charAt(0).toUpperCase() + str.slice(1);
    return capital;
}
 */

//----------------------------------------------------

// Ques 40 - Count the Number of Vowels
/*
const vowels = ['a','e','i','o','u'];
const string = "Yashika";
const result = countvowels(string);
console.log(result);
function countvowels(str){
    let cnt =0;
    for(let letter of str.toLowerCase()){
        if(vowels.includes(letter)){
            cnt++;
        }
    }
}
 */

//---------------------------------------------------

//Qyes 41 - Remove a Property from an Object
/*

const std = {
    name: 'yashika',
    age: 20,
    greet : function(){
        console.log("Hello");
    }
}
delete std.greet;
console.log(std);
 */

//----------------------------------------------------

// Ques 42 - check if a string starts with 'S' and ends with 'G'

/*
let string = 'Sehag';
checkString(string);
function checkString(str) {
    if(str.startsWith('S') && str.endsWith('G')) {
        console.log('The string starts with S and ends with G');
    }
    else if(str.startsWith('S')) {
        console.log('The string starts with S but does not end with G');
    }
     else if(str.endsWith('G')) {
        console.log('The string starts does not with S but end with G');
    }
    else {
        console.log('The string does not start with S and does not end with G');
    }
}
 */

//---------------------------------------------------------------

// Ques 43 -  Check if a Key Exists in an Object
/*
const person = {
    id: 1,
    name: 'John',
    age: 23
}
const hasKey = 'name' in person;
if(hasKey) {
    console.log('The key exists.');
}
else {
    console.log('The key does not exist.');
}
 */

//--------------------------------------------------------------

//Ques 44 - Clone the Object Using Object.assign()

/*
const person = {
    name: 'yashika',
    age: 20,
}
const cloneperson = Object.assign({}, person);
cloneperson.name = 'arshit';
console.log(cloneperson);
 */

//--------------------------------------------------------------

//Ques 45 Loop through an object 

/*
const person = {
    name: 'yashika',
    age: 20,
}
for(let key in person){
    let value;
    value = person[key];
    console.log(key + " - " + value);
}
 */

//--------------------------------------------------------------

//Ques 46 - Merge properties of 2 sets

/*
 const person1 = {
    name: 'yashika',
    age: 20,
}
const person2 = {
    gender: 'female'
}
const newobj = Object.assign(person1, person2);
console.log(newobj);
const newObj = {...person1, ...person2};
console.log(newObj);
 */

//--------------------------------------------------------------

//Ques 47 - Count the Number of Keys/Properties in an Object
/*
const person = {
    name: 'yashika',
    age: 20,
}
let cnt = 0;
for(let key in person){
    cnt += 1;
}
console.log(cnt);
*/

//--------------------------------------------------------------

//Ques 48 - Add a key value pain in an object 

/*
const person = {
    name: 'yashika',
    age: 20,
}
person.height = 5.7;
console.log(person);
 */


//--------------------------------------------------------------

//Ques 49 - Replace All Occurrences of a String

/*
const string = 'Mr red has a red house and a red car';
const result = string.split('red').join('blue');
console.log(result);
*/

//--------------------------------------------------------------

//Ques 50 -  Create Multiline Strings
/*
const message = 'This is a long message\n' + 
    'that spans across multiple lines\n' + 
    'in the code.'
console.log(message);

*/





